import Head from "next/head";
import Homepage from "./homepage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Anant Kumawat ✦</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>
      <Homepage/>
    </>
  );
}
